inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

Naming/MethodParameterName:
  MinNameLength: 1

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Performance/Sum:
  Enabled: false
